### PR TITLE
a better example

### PR DESCRIPTION
**Pull request by anupvarghese**
Added some modification for a better example

### CODE REVIEW

**Comment by HriBB** [comment]
Hey there. This was just an idea I had a few months ago. If you're interested, we can make something out of it ;)

**Comment by anupvarghese** [comment]
Cool... Sure.. Happy to contribute :)

**Comment by HriBB** [comment]
So as I already mentioned, this was just an idea I had a few months ago, I'm not sure if it is a good one :)  I don't know enough about reactjs and paperjs yet ...

Things get tricky when you try to do some more complex stuff. For example in one of my apps I use a lot of matrix tranforms to enable canvas pan and zoom when user does pinch-zoom or mouse-wheel-zoom, and I simply can't figure out a good way to do this.

We could start with something simple, then build up, maybe port some of the examples, then gradually attack the hard stuff ... What do you think?

**Comment by anupvarghese** [comment]
I think this is a good idea. I was doing some simple application using these libraries.. 
As you mentioned some of the best stuffs to do are
- [ ] rasterization
- [ ] zoom
- [ ] export as SVG or JSON
- [ ] Keyboard and mouse controls 
- [ ] Free drawing and 2D shapes etc...

**Comment by HriBB** [comment]
Exactly!

First I want to create a simple example where you can dynamically add/remove layers/items. Roughly something like this

Initial render

```
render() {
  <Paper>
    <Layer>
      <Circle
        center={[100, 100]}
        radius={50}
        fillColor={'blue'}/>
    </Layer>
  </Paper>
}
```

Then user click on button to add another layer so we end up with something like this

```
render() {
  <Paper>
    <Layer>
      <Circle
        center={[100, 100]}
        radius={50}
        fillColor={'blue'}/>
    </Layer>
    <Layer>
      <Circle
        center={[200, 200]}
        radius={100}
        fillColor={'green'}/>
    </Layer>
  </Paper>
}
```

So basically one could do something like this

```
render() {
  const { layers } = this.props
  <Paper>
    {layers.map(layer =>
      <Layer>
        {layer.items.map(item => {
          switch (item.type) {
            case 'line':   return <Line {...item} />
            case 'circle': return <Circle {...item} />
          }
        })}
      </Layer>
    )}
  </Paper>
}

```

Then I want to move quickly to the hard stuff such as pan/zoom.

I'm pretty busy ATM, so if you're interested, we can work together on this. I can give you full access to the repo, or you can just fork it and play around ;)

**Comment by anupvarghese** [comment]
Interesting. Yup I'm interested, let's work on it. Need to add some tests as well. I am also a little busy now, but will work on this whenever I m free. Cheers..

**Comment by HriBB** [comment]
@anupvarghese check out the [React Fiber renderer](https://github.com/HriBB/react-paper-bindings/blob/master/src/react-paper-bindings.js) I created. Let me know what you think ;)

**Comment by anupvarghese** [comment]
@HriBB That looks awesome. I will take a detailed look over the weekend. 👍

**Pull request merged**
